spring.application.name=benchmark-api

cognodb.uri=bolt+s://db-f1a1fde3.databases.cognodb.com
cognodb.username=cognodb
cognodb.password=489a63e1dcfc087a82832981f2578216



dataset.url=https://snap.stanford.edu/data/wiki-Vote.txt.gz
dataset.directory=dataset
dataset.filename=wiki-Vote.txt.gz